# This file was generated by GoReleaser. DO NOT EDIT.
cask "leftmark" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "fbc409cf7b07639b02d29f040bc4de96f7939fba54e51f195b64de9ac4ff795f"
      url "https://github.com/issam-assiyadi/leftmark/releases/download/v#{version}/leftmark_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "489c7adf4643254f9a10ce9cb2600368e8cf40af45b51d2bba477700d27781f0"
      url "https://github.com/issam-assiyadi/leftmark/releases/download/v#{version}/leftmark_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4a5c12a641130942ef0e042eaa8018176dd8cfe7e278320343c3a5399a67f76e"
      url "https://github.com/issam-assiyadi/leftmark/releases/download/v#{version}/leftmark_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "823274c7de3539748d677c08870fd57e278f06ad0f0c2c2fe7e3a6b4ca3ed5a9"
      url "https://github.com/issam-assiyadi/leftmark/releases/download/v#{version}/leftmark_linux_amd64.tar.gz"
    end
  end

  name "leftmark"
  desc "A scanner for the TODOs, FIXMEs, notes, and questions you already leave in your codebase."
  homepage "https://github.com/issam-assiyadi/leftmark"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "leftmark"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/leftmark"]
    end
  end

  # No zap stanza required
end
